# escape=`
FROM  mcr.microsoft.com/azure-powershell:latest

# install git
RUN apt-get update && apt-get install -y git

# clone GuardrailsSolutionAccelerator repo
RUN git clone https://github.com/mbrat2005/GuardrailsSolutionAccelerator.git

# checkout container-instance-test branch
RUN git -C GuardrailsSolutionAccelerator checkout container-instance-test

# create directory for extracted modules
RUN mkdir /GuardrailsSolutionAccelerator/extractedModules

# switch to powershell
SHELL ["pwsh", "-command"]

# unzip zipped modules to module directory
RUN Set-Location /root/.local/share/powershell/Modules; Get-ChildItem -Path "/GuardrailsSolutionAccelerator/psmodules/*.zip" | ForEach-Object { $_ | Expand-Archive -DestinationPath $_.BaseName -ErrorAction Stop }

# install OMS Ingestion API Module
RUN Install-Module -Name OMSIngestionAPI -Force